import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { FormEvent, useEffect, useState } from 'react';
import { useRecoilState } from 'recoil';
import styled from 'styled-components';
import { userState } from '../atoms/user';
import Modal from '../components/domain/Modal';

const Home: NextPage = () => {
  const [visible, setVisible] = useState(false);
  const [user, setUser] = useRecoilState(userState);
  const [userName, setUserName] = useState('');

  useEffect(() => {
    if (user.name.length === 0) {
      setVisible(true);
    }
  }, []);

  const handleUserModal = (e: FormEvent<HTMLFormElement>) => {
    setUser({ name: userName });
    setVisible(false);
    setUserName('');
  };

  return (
    <>
      <Head>
        <title>Real time application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {visible ? (
        <Modal visible={visible} onClose={() => setVisible(false)}>
          <form onSubmit={handleUserModal}>
            <input
              value={userName}
              onChange={(e) => setUserName(e.target.value)}
            ></input>
            <button> 확인 </button>
          </form>
        </Modal>
      ) : (
        <StyledContainer>
          <StyledTitle>Try Real Time App</StyledTitle>
          <CardWrapper>
            <Link href="/chat">
              <Card>Real time chat</Card>
            </Link>
          </CardWrapper>
        </StyledContainer>
      )}
    </>
  );
};

const StyledContainer = styled.main`
  min-height: 100vh;
  padding: 4rem 0;
  flex: 1;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`;

const StyledTitle = styled.h1`
  margin: 0;
  line-height: 1.15;
  font-size: 3rem;
`;

const CardWrapper = styled.div`
  display: flex;
  align-items: center;
  justify-content: center;
  flex-wrap: wrap;
  max-width: 800px;
`;

const Card = styled.a`
  margin: 1.5rem;
  padding: 1.5rem;
  text-align: left;
  color: inherit;
  text-decoration: none;
  border: 1px solid #eaeaea;
  border-radius: 10px;
  transition: color 0.15s ease, border-color 0.15s ease;
  width: 200px;
  background-color: #e1e3c4;
  text-align: center;

  cursor: pointer;
  &:hover,
  &:focus,
  &:active {
    color: #0070f3;
    border-color: #0070f3;
    background-color: skyblue;
  }
`;

export default Home;
