import type { NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';
import { io } from 'socket.io-client';
import styles from '../styles/Home.module.css';

const socket = io(`http://localhost:8000`, {
  transports: ['websocket'],
});

const Home: NextPage = () => {
  const [chat, setChat] = useState('');
  const [chatList, setChatList] = useState<string[]>([]);

  const handleChat = () => {
    socket.emit('first', {
      post: chat,
    });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Real time chatting</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <br />
        <input type="text" onChange={(e) => setChat(e.target.value)} />
        <button onClick={handleChat}> send </button>
      </div>

      {chatList.length > 0 && chatList?.map((chat) => `<li>${chat}</li>`)}
    </div>
  );
};

export default Home;
